(function(g){var window=this;var sza=function(a,b,c,d){var e=b.jc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.qd(c,d?d:"mqdefault.jpg");var k=b instanceof g.CN?g.JV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.XP(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.CN?b.za:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Pn(c),is_live:m,is_list:l,
is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.ZP&&(c.playlist_length=b.getLength());a.update(c)},n5=function(a,b){g.GH.call(this,{G:"div",
aa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},o5=function(a){var b={G:"span",
L:"ytp-upnext-top",J:[{G:"span",L:"ytp-upnext-header",J:[g.U("YTP_PLAYLIST_UP_NEXT")]},{G:"span",L:"ytp-upnext-title",J:["{{title}}"]},{G:"span",L:"ytp-upnext-author",J:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={G:"div",L:"ytp-upnext",T:{"aria-label":"{{watch}}"},J:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},b,{G:"a",L:"ytp-upnext-autoplay-icon",T:c,J:[{G:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
J:[{G:"circle",L:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",J:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
J:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]}]};g.V.call(this,b);this.A=null;b=this.va["ytp-upnext-cancel"];this.A=new g.V({G:"button",aa:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":g.U("YTP_AUTOPLAY_CANCEL")},J:[g.U("YTP_CANCEL")]});g.M(this,this.A);this.A.R("click",this.MO,this);this.A.wa(b);this.l=a;this.I=this.va["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.B=null;this.F=new g.Xt(this.fn,5E3,this);g.M(this,this.F);this.H=0;this.O(this.va["ytp-upnext-autoplay-icon"],"click",
this.WQ);this.fB();this.O(a,"autonavvisibility",this.fB);this.O(a,"mdxnowautoplaying",this.kQ);this.O(a,"mdxautoplaycanceled",this.lQ);this.O(a,"mdxautoplayupnext",this.JD);3==this.l.Ta()&&(a=(a=g.OU(g.JU(this.l)))?a.aI():null)&&this.JD(a)},tza=function(a,b){a.B=b;
sza(a,b,g.X(a.l),"hqdefault.jpg")},p5=function(a,b){if(!a.o){g.PF("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.B.title);
a.H=g.aG();a.o=new g.Xt((0,g.z)(a.pq,a,b),25);a.pq(b);var c=b||g.X(a.l).experiments.l("autoplay_time")||1E4;a.l.sa("onAutonavCoundownStarted",c)}g.uq(a.element,"ytp-upnext-autoplay-paused")},r5=function(a){q5(a);
a.H=g.aG();a.pq();g.S(a.element,"ytp-upnext-autoplay-paused")},q5=function(a){a.o&&(a.o.dispose(),a.o=null)},s5=function(a,b){b=void 0===b?!1:b;
var c=g.X(a.l);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.YU(a.l,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.jc(),a.fn(),a.C=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.qd(c)}),a.D=a.O(a.C,"click",a.MQ),a.F.start())}q5(a);a.l.Kj(!1,b)},uza=function(a){n5.call(this,a,"subscribecard-endscreen");
var b=a.ea();this.o=new g.V({G:"div",L:"ytp-subscribe-card",J:[{G:"img",L:"ytp-author-image",T:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",J:[{G:"div",L:"ytp-author-name",J:[b.author]},{G:"div",L:"html5-subscribe-button-container"}]}]});g.M(this,this.o);this.o.wa(this.element);this.A=new g.i_(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Tl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.A);this.A.wa(this.o.va["html5-subscribe-button-container"]);this.hide()},
t5=function(a){var b=g.X(a),c=g.AJ||g.$e?{style:"will-change: opacity"}:void 0,d=b.l&&!b.D,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",aa:e,T:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",L:"ytp-videowall-still-image",T:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",J:[{G:"span",L:"ytp-videowall-still-info-bg",J:[{G:"span",L:"ytp-videowall-still-info-content",T:c,J:[{G:"span",L:"ytp-videowall-still-info-title",J:["{{title}}"]},{G:"span",L:"ytp-videowall-still-info-author",
J:["{{author_and_views}}"]},{G:"span",L:"ytp-videowall-still-info-live",J:[g.U("YTP_LIVE")]},{G:"span",L:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",aa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",aa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
J:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.A=d;this.l=a;this.o=null;this.R("click",this.B);this.R("keypress",this.C);g.X(a).W&&(a=a.app.ca,b=this.element,g.Ma(a.g,b),g.Pa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.Ve(this,(0,g.z)(a.D,a,b)))},u5=function(a){n5.call(this,a,"videowall-endscreen");
this.K=a;this.F=0;this.A=[];this.H=this.D=this.C=null;this.I=this.X=!1;this.B=new g.yF(this);g.M(this,this.B);this.M=new g.Xt(g.Da(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.M);var b=new g.V({G:"button",aa:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":g.U("YTP_PREVIOUS")},J:[g.Hna()]});g.M(this,b);b.wa(this.element);b.R("click",this.OM,this);this.N=new g.AH({G:"div",L:"ytp-endscreen-content"});g.M(this,this.N);this.N.wa(this.element);b=new g.V({G:"button",aa:["ytp-button","ytp-endscreen-next"],
T:{"aria-label":g.U("YTP_NEXT")},J:[g.Ina()]});g.M(this,b);b.wa(this.element);b.R("click",this.NM,this);this.o=new o5(a);g.M(this,this.o);g.kV(this.l,this.o.element,4);this.hide()},v5=function(a){return g.lV(a.l)&&a.uq()&&!a.H},vza=function(a){return(0,g.H)(a.suggestions,function(a){return g.ZY(a)})},w5=function(a){var b=a.Dt();
b!=a.X&&(a.X=b,a.l.P("autonavvisibility"))},x5=function(a){g.qV.call(this,a);
g.EG({YTP_AUTOPLAY_CANCEL:"Annuller autoplay",YTP_AUTOPLAY_NEXT:"Afspil n\u00e6ste video",YTP_AUTOPLAY_PAUSED_3:"Autoplay er sat p\u00e5 pause",YTP_CANCEL:"Annuller",YTP_MIX:"Mix",YTP_PLAYLIST_UP_NEXT:"N\u00e6ste",YTP_UNSUBSCRIBE:"Afmeld abonnement"});this.l=null;this.o=new g.yF(this);g.M(this,this.o);this.A=g.X(a);wza(a)?this.l=new u5(this.g):this.A.da?this.l=new uza(this.g):this.l=new n5(this.g);g.M(this,this.l);g.kV(this.g,this.l.element,4);this.uC();this.o.O(a,"videodatachange",this.uC,this);
this.o.O(a,"crn_endscreen",this.WK,this);this.o.O(a,"crx_endscreen",this.XK,this)},wza=function(a){a=g.X(a);
return a.Ad&&!a.da};
g.p(n5,g.GH);n5.prototype.create=function(){this.created=!0};
n5.prototype.destroy=function(){this.created=!1};
n5.prototype.uq=function(){return!1};
n5.prototype.Dt=function(){return!1};g.p(o5,g.V);g.h=o5.prototype;g.h.fn=function(){this.C&&(this.F.stop(),this.Ba(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.fB=function(){g.FH(this,g.KU(this.l))};
g.h.MQ=function(){window.focus();this.fn()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.pq=function(a){a=a||g.X(this.l).experiments.l("autoplay_time")||1E4;var b=Math.min(g.aG()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.l.Ta()?s5(this,!0):this.o&&this.o.start()};
g.h.WQ=function(a){!g.Kd(this.A.element,g.nF(a))&&g.lX(a,this.l)&&s5(this)};
g.h.MO=function(){g.MU(this.l,!0)};
g.h.kQ=function(a){this.l.Ta();this.show();p5(this,a)};
g.h.JD=function(a){this.l.Ta();this.B&&this.B.jc().videoId==a.jc().videoId||tza(this,a)};
g.h.lQ=function(){this.l.Ta();q5(this);this.hide()};
g.h.U=function(){q5(this);this.fn();g.V.prototype.U.call(this)};g.p(uza,n5);g.p(t5,g.V);t5.prototype.Zj=function(){g.oV(this.l,this.element);var a=this.o.jc().videoId,b=this.o.getPlaylistId();g.h0(this.l.app,a,this.o.be,b,void 0,void 0,void 0)};
t5.prototype.B=function(a){g.lX(a,this.l,this.A,this.o.be||void 0)&&this.Zj()};
t5.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.sF(a)||(this.Zj(),g.rF(a))}};g.p(u5,n5);g.h=u5.prototype;g.h.create=function(){n5.prototype.create.call(this);var a=this.l.ea();a&&(this.C=vza(a),this.D=a);this.Eg();this.B.O(this.l,"appresize",this.Eg);this.B.O(this.l,"onVideoAreaChange",this.Eg);this.B.O(this.l,"videodatachange",this.PM);this.B.O(this.l,"autonavchange",this.iA);this.B.O(this.l,"autonavcancel",this.MM);this.B.O(this.element,"transitionend",this.iS)};
g.h.destroy=function(){g.AF(this.B);g.Xe(this.A);this.A=[];this.C=null;n5.prototype.destroy.call(this);g.uq(this.element,"ytp-show-tiles");this.M.stop()};
g.h.uq=function(){return 1!=this.D.autonavState};
g.h.show=function(){n5.prototype.show.call(this);g.uq(this.element,"ytp-show-tiles");g.X(this.l).g?g.Zt(this.M):this.M.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.MU(this.l,!1);var a=v5(this);g.lV(this.l)&&g.X(this.l).experiments.g("ui_logging")&&g.YU(this.l,"end",{cancelButtonShow:a?"1":"0",state:this.uq()?"enabled":"disabled"});a?(w5(this),2==this.D.autonavState?g.X(this.l).experiments.g("fast_autonav_in_background")&&3==this.l.Bi()?s5(this.o,!0):p5(this.o):3==this.D.autonavState&&
r5(this.o)):(g.MU(this.l,!0),w5(this))};
g.h.hide=function(){n5.prototype.hide.call(this);r5(this.o);w5(this)};
g.h.iS=function(a){g.nF(a)==this.element&&this.Eg()};
g.h.Eg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");if(g.X(this.K).experiments.g("web_player_endscreen_size_killswitch"))var a=g.Ih(this.element);else{a=g.aV(this.K);var b=g.UH(this.K);b&&(b=b.Fd()?48:32,a.width-=2*b)}var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,B=e<=k-2&&n>=q*m;if((q+
1)/r*d/c>c/(q/(r+1)*d)&&B)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(B)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Xc(a.width/m||1,1,1.21);n*=g.Xc(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Hh(a,m,n);g.nh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});tza(this.o,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",v5(this));w5(this);m+=4;
n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.Yc(q+this.F,l),0!=r){u=this.A[c];u||(u=new t5(this.l),this.A[c]=u,a.appendChild(u.element));B=Math.floor(n*k/e);var F=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-B-4,Y=Math.floor(m*(f+r)/b)-F-4;g.wh(u.element,F,B);g.Hh(u.element,Y,L);g.nh(u.element,"transitionDelay",(k+f)/20+"s");g.T(u.element,"ytp-videowall-still-mini",1==r);g.T(u.element,"ytp-videowall-still-large",2<r);r=u;
q=this.C[q];r.o=q;sza(r,q,g.X(r.l),g.sq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");u=q.be;q=r.l;g.X(q).W&&(q=q.app.ca,r=r.element,u=u&&u.itct,B=r.getAttribute("data-visual-id"),g.Ma(q.g,r),g.mV(q,"onLogServerVeCreated",{id:B,tracking_params:u}));c++}g.T(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Dd(e.element),g.We(e);this.A.length=c}};
g.h.PM=function(){var a=this.l.ea();this.D!=a&&(this.F=0,this.C=vza(a),this.D=a,this.Eg())};
g.h.NM=function(){this.F+=this.A.length;this.Eg()};
g.h.OM=function(){this.F-=this.A.length;this.Eg()};
g.h.dK=function(){return!!this.o.o};
g.h.iA=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,q5(this.o),this.g&&this.Eg()):(this.I=!0,this.g&&v5(this)&&(2==a?p5(this.o):3==a&&r5(this.o)))};
g.h.MM=function(a){if(a){for(a=0;a<this.A.length;a++)g.pV(this.K,this.A[a].element,!0);this.iA(1)}else this.H=null,this.I=!1;this.Eg()};
g.h.Dt=function(){return this.g&&v5(this)};g.p(x5,g.qV);g.h=x5.prototype;g.h.Kz=function(){var a=this.g.ea(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!wza(this.g)||b;a=g.VN(a,"ypc_module");var c=g.i0(this.g.app);return b&&!a&&!c};
g.h.Jz=function(){return this.l.Dt()};
g.h.ZJ=function(){return this.Jz()?this.l.dK():!1};
g.h.U=function(){g.gV(this.g,"endscreen");g.qV.prototype.U.call(this)};
g.h.load=function(){g.qV.prototype.load.call(this);this.l.show();g.X(this.g).da&&.01>Math.random()&&g.YU(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.qV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.WK=function(a){this.Kz()&&(this.l.created||this.l.create(),"load"==a.ia&&this.load())};
g.h.XK=function(a){"load"==a.ia&&this.loaded&&this.unload()};
g.h.uC=function(){g.gV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ea().lengthSeconds-10),0);a=new g.UP(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.UP(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.dV(this.g,[a,b])};g.eY.endscreen=x5;})(_yt_player);
